### ISSUE TITLE
FW5

### ISSUE THREAD

**Issue by iFac3** [biemond/com.athom.philipsair#8]
Hi! Since fw5 release I have to restart Philips Air app in every 1-2 days. Device become “undefinied” after a while.

**Comment by biemond** [comment]
He,  I see this in the crash log

don't you have sticky dhcp , I see not found.


Error: getaddrinfo ENOTFOUND ik
   at Remote IPC Process

Emitted 'error' event on SocketWrapper instance at:
    at Socket. (/node_modules/node-coap-client/build/lib/SocketWrapper.js:16:18)
    at Socket.emit (events.js:311:20)
    at dgram.js:666:33
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  message: 'getaddrinfo ENOTFOUND ik',
  code: 'ENOTFOUND'
}

**Comment by iFac3** [comment]
Hi, IP is fixed, no change for a very long.

Rgds,

Geri

**Comment by biemond** [comment]
oh weird , undefined, what version of homey + software are you using?  maybe run out of mem. but I need to see the stacktrace.

**Comment by iFac3** [comment]
Latest, all. FW5, 0.0.27 app, 6.3.669 iOS app.

Geri

**Comment by iFac3** [comment]
Has just happened again. I restarted app 5-6 times, then it became available.

![030F8CB7-8A8C-411D-A230-D78AEFD51FAD](https://user-images.githubusercontent.com/51527573/109066137-e7e78000-76ec-11eb-981d-2482bffb4fd7.jpeg)

![4C6569EC-F758-4FDD-93A5-2C28E8D7988D](https://user-images.githubusercontent.com/51527573/109066151-eddd6100-76ec-11eb-996c-d7d9e840fc9c.jpeg)

![F399CB96-8B6E-4AC4-B865-6664151A5367](https://user-images.githubusercontent.com/51527573/109066170-f3d34200-76ec-11eb-8067-31dc0176a299.jpeg)

**Comment by biemond** [comment]
ah maybe I cannot reach it, I think it is a key issue and try to get a new key. 

how stable is your wifi, maybe use  a different 2.4 channel
